resources:
   - name: sample_java_file_test
     type: file
     fileUrl: text.js
     configuration:
        integrationName: docker-int
     initialVersion:
       fileName: test
       fileDtTm: test

pipelines:
  - name: test_pipeline_1
    setup:
      environmentVariables:
        normal:
          - ENV1: value-pipe-1
          - ENV2: value-pipe-2
        encrypted:
          - SECURE_ENV1: test_value-pipe-1
          - SECURE_ENV2: test_value-pipe-2
      runtime: onHost-pipe
    steps:
      - name: main_step
        type: runSh
        configuration:
          affinityGroup: test_group 
          priority: 9999
          timeoutSeconds: 40
          cache: true
        setup:
          environmentVariables:
            normal:
              - ENV1: value1
              - ENV2: value2
            encrypted:
              - SECURE_ENV1: test_value
              - SECURE_ENV2: test_value
          runtime: onHost
        requires:
          resources:
            - sample_java_file_test
        execution:
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
