language: java

build:
  ci:
    - echo "here_6"

jobs:
  - name: runSh_0
    type: runSh
    steps:
      - OUT: nginx_1 
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state nginx_1 versionName runSh_0_$BUILD_NUMBER


resources:
  - name: nginx_1
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
